"""Add estimated_value and marginal_benefit fields to Product model

Revision ID: 95686921ced2
Revises: 
Create Date: 2024-08-12 00:34:26.683978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95686921ced2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('marginal_benefit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('marginal_benefit')
        batch_op.drop_column('estimated_value')

    # ### end Alembic commands ###
